name: "Setup JFrog CLI OIDC Example"
on: push

env:
  JFROG_CLI_AVOID_NEW_VERSION_WARNING: 'true'
  
permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ vars.JF_URL }} 
        with:
          oidc-provider-name: setup-jfrog-cli 
          oidc-audience: jfrog-github
          
      - name: Build with Maven
        run: mvn package

      - name: Run JFrog CLI
        run: | 
          # Ping the server
          jf rt ping
          # Collect environmnt variables for the build
          jf rt bce
          # Collect VCS details from git and add them to the build
          jf rt bag
          # Publish build info
          jf rt bp
        
