name: "Setup JFrog CLI OIDC Example"
on: push

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4.5.11
        env:
          JF_URL: https://diamond.jfrog.io 
        with:
          oidc-provider-name: setup-jfrog-cli 
          
      - name: Build with Maven
        run: mvn package
        
